spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tSJrsiEEKwXCHcYoMJR
      secret-key: EqZmNwiPLKtg4R1PK6GFldcuIn79Ol
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
  application:
    name: gulimall-third-party
server:
  port: 30000