spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tSJrsiEEKwXCHcYoMJR
      secret-key: EqZmNwiPLKtg4R1PK6GFldcuIn79Ol
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        appcode: 1780ac457fb747b3b62765ca3b65137c
        template-id: CST_ptdie100
        method: POST

  application:
    name: gulimall-third-party
server:
  port: 30000